### ISSUE TITLE
Would you mind adding Android config ? 

### ISSUE THREAD

**Issue by alexgomes09** [prsolucoes/pdfium-lib#8]
Thanks for your support

**Comment by prsolucoes** [comment]
Hi,

Yes, i will add all and will rename it as pdfium or something like this.

I have scripts for all systems.

I fixed ios and macos to use latest release.

I will write here when it is ready.

Thanks.

**Comment by prsolucoes** [comment]
Hi @alexgomes09,

I have added support for android. Download binaries on releases page:
https://github.com/prsolucoes/pdfium-lib/releases

Thanks.
